default: &default
  adapter: mysql2
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: "root"
  password: "05102000"
  host: "localhost"
  # port: 3306
  # socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: "order_food_system_development"

test:
  <<: *default
  database: "order_food_system_test"

production:
  <<: *default
  database: "order_food_system_production"
  # username: ruby_naitei_2022_order_food_system
  # password: <%= ENV['RUBY_NAITEI_2022_ORDER_FOOD_SYSTEM_DATABASE_PASSWORD'] %>
